/**
 * UI string translations for Spire Archive.
 * Usage:
 *   import { t } from '../lib/ui-strings';
 *   t('Cards', locale)  // → 'カード' when locale='ja'
 */

import type { Locale } from './data';

const strings: Record<string, Partial<Record<Locale, string>>> = {
  // Nav
  'Characters': { ja: 'キャラクター', ko: '캐릭터', zh: '角色', de: 'Charaktere', fr: 'Personnages', es: 'Personajes', pt: 'Personagens', it: 'Personaggi', pl: 'Postacie', ru: 'Персонажи', tr: 'Karakterler', th: 'ตัวละคร' },
  'Cards': { ja: 'カード', ko: '카드', zh: '卡牌', de: 'Karten', fr: 'Cartes', es: 'Cartas', pt: 'Cartas', it: 'Carte', pl: 'Karty', ru: 'Карты', tr: 'Kartlar', th: 'การ์ด' },
  'Relics': { ja: 'レリック', ko: '유물', zh: '遗物', de: 'Relikte', fr: 'Reliques', es: 'Reliquias', pt: 'Relíquias', it: 'Reliquie', pl: 'Relikty', ru: 'Реликвии', tr: 'Kalıntılar', th: 'เรลิค' },
  'Potions': { ja: 'ポーション', ko: '물약', zh: '药水', de: 'Tränke', fr: 'Potions', es: 'Pociones', pt: 'Poções', it: 'Pozioni', pl: 'Mikstury', ru: 'Зелья', tr: 'İksirler', th: 'ยา' },
  'Monsters': { ja: 'モンスター', ko: '몬스터', zh: '怪物', de: 'Monster', fr: 'Monstres', es: 'Monstruos', pt: 'Monstros', it: 'Mostri', pl: 'Potwory', ru: 'Монстры', tr: 'Canavarlar', th: 'มอนสเตอร์' },
  'Events': { ja: 'イベント', ko: '이벤트', zh: '事件', de: 'Ereignisse', fr: 'Événements', es: 'Eventos', pt: 'Eventos', it: 'Eventi', pl: 'Zdarzenia', ru: 'События', tr: 'Etkinlikler', th: 'เหตุการณ์' },
  'Buffs & Debuffs': { ja: 'バフ＆デバフ', ko: '버프 & 디버프', zh: '增益与减益', de: 'Buffs & Debuffs', fr: 'Effets', es: 'Efectos', pt: 'Efeitos', it: 'Effetti', pl: 'Efekty', ru: 'Эффекты', tr: 'Etkiler', th: 'บัฟและดีบัฟ' },
  'Enchantments': { ja: 'エンチャント', ko: '인챈트', zh: '附魔', de: 'Verzauberungen', fr: 'Enchantements', es: 'Encantamientos', pt: 'Encantamentos', it: 'Incantesimi', pl: 'Zaklęcia', ru: 'Зачарования', tr: 'Büyüler', th: 'เสน่ห์' },
  'Keywords': { ja: 'キーワード', ko: '키워드', zh: '关键词', de: 'Schlüsselwörter', fr: 'Mots-clés', es: 'Palabras clave', pt: 'Palavras-chave', it: 'Parole chiave', pl: 'Słowa kluczowe', ru: 'Ключевые слова', tr: 'Anahtar Kelimeler', th: 'คำสำคัญ' },
  'Search': { ja: '検索', ko: '검색', zh: '搜索', de: 'Suche', fr: 'Recherche', es: 'Buscar', pt: 'Buscar', it: 'Cerca', pl: 'Szukaj', ru: 'Поиск', tr: 'Ara', th: 'ค้นหา' },

  // Card detail
  'Applied Effects': { ja: '適用効果', ko: '적용 효과', zh: '应用效果', de: 'Angewandte Effekte', fr: 'Effets appliqués', es: 'Efectos aplicados', pt: 'Efeitos aplicados', it: 'Effetti applicati', pl: 'Zastosowane efekty', ru: 'Применённые эффекты', tr: 'Uygulanan Etkiler', th: 'เอฟเฟกต์ที่ใช้' },
  'Base': { ja: '基本', ko: '기본', zh: '基础', de: 'Basis', fr: 'Base', es: 'Base', pt: 'Base', it: 'Base', pl: 'Bazowa', ru: 'Базовая', tr: 'Temel', th: 'พื้นฐาน' },
  'Upgraded': { ja: '強化', ko: '업그레이드', zh: '升级', de: 'Aufgewertet', fr: 'Améliorée', es: 'Mejorada', pt: 'Melhorada', it: 'Potenziata', pl: 'Ulepszona', ru: 'Улучшенная', tr: 'Yükseltilmiş', th: 'อัปเกรด' },
  'Cost': { ja: 'コスト', ko: '비용', zh: '费用', de: 'Kosten', fr: 'Coût', es: 'Coste', pt: 'Custo', it: 'Costo', pl: 'Koszt', ru: 'Стоимость', tr: 'Maliyet', th: 'ค่าใช้จ่าย' },
  'Type': { ja: 'タイプ', ko: '유형', zh: '类型', de: 'Typ', fr: 'Type', es: 'Tipo', pt: 'Tipo', it: 'Tipo', pl: 'Typ', ru: 'Тип', tr: 'Tür', th: 'ประเภท' },
  'Rarity': { ja: 'レア度', ko: '희귀도', zh: '稀有度', de: 'Seltenheit', fr: 'Rareté', es: 'Rareza', pt: 'Raridade', it: 'Rarità', pl: 'Rzadkość', ru: 'Редкость', tr: 'Nadirlik', th: 'ความหายาก' },
  'Character': { ja: 'キャラクター', ko: '캐릭터', zh: '角色', de: 'Charakter', fr: 'Personnage', es: 'Personaje', pt: 'Personagem', it: 'Personaggio', pl: 'Postać', ru: 'Персонаж', tr: 'Karakter', th: 'ตัวละคร' },

  // Card types
  'Attack': { ja: 'アタック', ko: '공격', zh: '攻击', de: 'Angriff', fr: 'Attaque', es: 'Ataque', pt: 'Ataque', it: 'Attacco', pl: 'Atak', ru: 'Атака', tr: 'Saldırı', th: 'โจมตี' },
  'Skill': { ja: 'スキル', ko: '스킬', zh: '技能', de: 'Fertigkeit', fr: 'Compétence', es: 'Habilidad', pt: 'Habilidade', it: 'Abilità', pl: 'Umiejętność', ru: 'Навык', tr: 'Beceri', th: 'ทักษะ' },
  'Power': { ja: 'パワー', ko: '파워', zh: '能力', de: 'Kraft', fr: 'Pouvoir', es: 'Poder', pt: 'Poder', it: 'Potere', pl: 'Moc', ru: 'Сила', tr: 'Güç', th: 'พลัง' },
  'Curse': { ja: '呪い', ko: '저주', zh: '诅咒', de: 'Fluch', fr: 'Malédiction', es: 'Maldición', pt: 'Maldição', it: 'Maledizione', pl: 'Klątwa', ru: 'Проклятие', tr: 'Lanet', th: 'คำสาป' },
  'Status': { ja: 'ステータス', ko: '상태', zh: '状态', de: 'Status', fr: 'Statut', es: 'Estado', pt: 'Estado', it: 'Stato', pl: 'Status', ru: 'Статус', tr: 'Durum', th: 'สถานะ' },
  'Quest': { ja: 'クエスト', ko: '퀘스트', zh: '任务', de: 'Quest', fr: 'Quête', es: 'Misión', pt: 'Missão', it: 'Missione', pl: 'Misja', ru: 'Задание', tr: 'Görev', th: 'เควส' },

  // Rarities
  'Common': { ja: 'コモン', ko: '일반', zh: '普通', de: 'Gewöhnlich', fr: 'Commun', es: 'Común', pt: 'Comum', it: 'Comune', pl: 'Pospolita', ru: 'Обычная', tr: 'Sıradan', th: 'ธรรมดา' },
  'Uncommon': { ja: 'アンコモン', ko: '고급', zh: '罕见', de: 'Ungewöhnlich', fr: 'Peu commun', es: 'Poco común', pt: 'Incomum', it: 'Non comune', pl: 'Rzadka', ru: 'Необычная', tr: 'Nadir', th: 'ไม่ธรรมดา' },
  'Rare': { ja: 'レア', ko: '희귀', zh: '稀有', de: 'Selten', fr: 'Rare', es: 'Rara', pt: 'Rara', it: 'Rara', pl: 'Bardzo rzadka', ru: 'Редкая', tr: 'Ender', th: 'หายาก' },
  'Basic': { ja: 'ベーシック', ko: '기본', zh: '基础', de: 'Basis', fr: 'Basique', es: 'Básica', pt: 'Básica', it: 'Base', pl: 'Podstawowa', ru: 'Базовая', tr: 'Temel', th: 'พื้นฐาน' },
  'Special': { ja: 'スペシャル', ko: '특수', zh: '特殊', de: 'Spezial', fr: 'Spécial', es: 'Especial', pt: 'Especial', it: 'Speciale', pl: 'Specjalna', ru: 'Особая', tr: 'Özel', th: 'พิเศษ' },

  // Character detail
  'Starting Deck': { ja: '初期デッキ', ko: '시작 덱', zh: '初始牌组', de: 'Startdeck', fr: 'Deck de départ', es: 'Mazo inicial', pt: 'Baralho inicial', it: 'Mazzo iniziale', pl: 'Startowa talia', ru: 'Стартовая колода', tr: 'Başlangıç Destesi', th: 'สำรับเริ่มต้น' },
  'Starting Relic': { ja: '初期レリック', ko: '시작 유물', zh: '初始遗物', de: 'Startrelikt', fr: 'Relique de départ', es: 'Reliquia inicial', pt: 'Relíquia inicial', it: 'Reliquia iniziale', pl: 'Startowy relikt', ru: 'Стартовая реликвия', tr: 'Başlangıç Kalıntısı', th: 'เรลิคเริ่มต้น' },

  // Filters
  'All': { ja: 'すべて', ko: '전체', zh: '全部', de: 'Alle', fr: 'Tous', es: 'Todos', pt: 'Todos', it: 'Tutti', pl: 'Wszystkie', ru: 'Все', tr: 'Tümü', th: 'ทั้งหมด' },
  'All Characters': { ja: '全キャラクター', ko: '모든 캐릭터', zh: '所有角色', de: 'Alle Charaktere', fr: 'Tous les personnages', es: 'Todos los personajes', pt: 'Todos os personagens', it: 'Tutti i personaggi', pl: 'Wszystkie postacie', ru: 'Все персонажи', tr: 'Tüm Karakterler', th: 'ตัวละครทั้งหมด' },
  'All Types': { ja: '全タイプ', ko: '모든 유형', zh: '所有类型', de: 'Alle Typen', fr: 'Tous les types', es: 'Todos los tipos', pt: 'Todos os tipos', it: 'Tutti i tipi', pl: 'Wszystkie typy', ru: 'Все типы', tr: 'Tüm Türler', th: 'ทุกประเภท' },
  'All Rarities': { ja: '全レア度', ko: '모든 희귀도', zh: '所有稀有度', de: 'Alle Seltenheiten', fr: 'Toutes les raretés', es: 'Todas las rarezas', pt: 'Todas as raridades', it: 'Tutte le rarità', pl: 'Wszystkie rzadkości', ru: 'Все редкости', tr: 'Tüm Nadirlikler', th: 'ความหายากทั้งหมด' },
  'All Tiers': { ja: '全ティア', ko: '모든 등급', zh: '所有级别', de: 'Alle Stufen', fr: 'Tous les niveaux', es: 'Todos los niveles', pt: 'Todos os níveis', it: 'Tutti i livelli', pl: 'Wszystkie poziomy', ru: 'Все уровни', tr: 'Tüm Seviyeler', th: 'ทุกระดับ' },
  'No results found': { ja: '結果が見つかりません', ko: '결과 없음', zh: '未找到结果', de: 'Keine Ergebnisse', fr: 'Aucun résultat', es: 'Sin resultados', pt: 'Nenhum resultado', it: 'Nessun risultato', pl: 'Brak wyników', ru: 'Ничего не найдено', tr: 'Sonuç bulunamadı', th: 'ไม่พบผลลัพธ์' },

  // Monster detail
  'HP': { ja: 'HP', ko: 'HP', zh: 'HP', de: 'HP', fr: 'PV', es: 'PV', pt: 'PV', it: 'PV', pl: 'HP', ru: 'HP', tr: 'HP', th: 'HP' },
  'Moves': { ja: '行動', ko: '행동', zh: '招式', de: 'Züge', fr: 'Actions', es: 'Movimientos', pt: 'Movimentos', it: 'Mosse', pl: 'Ruchy', ru: 'Действия', tr: 'Hareketler', th: 'การเคลื่อนไหว' },
  'Encounter Type': { ja: '遭遇タイプ', ko: '조우 유형', zh: '遭遇类型', de: 'Begegnungstyp', fr: "Type de rencontre", es: 'Tipo de encuentro', pt: 'Tipo de encontro', it: 'Tipo di incontro', pl: 'Typ spotkania', ru: 'Тип встречи', tr: 'Karşılaşma Türü', th: 'ประเภทการเผชิญหน้า' },

  // Encounter types
  'Normal': { ja: 'ノーマル', ko: '일반', zh: '普通', de: 'Normal', fr: 'Normal', es: 'Normal', pt: 'Normal', it: 'Normale', pl: 'Normalny', ru: 'Обычный', tr: 'Normal', th: 'ปกติ' },
  'Elite': { ja: 'エリート', ko: '엘리트', zh: '精英', de: 'Elite', fr: 'Élite', es: 'Élite', pt: 'Elite', it: 'Élite', pl: 'Elitarny', ru: 'Элитный', tr: 'Elit', th: 'อีลีท' },
  'Boss': { ja: 'ボス', ko: '보스', zh: 'Boss', de: 'Boss', fr: 'Boss', es: 'Jefe', pt: 'Chefe', it: 'Boss', pl: 'Boss', ru: 'Босс', tr: 'Patron', th: 'บอส' },
  'Weak': { ja: '弱敵', ko: '약적', zh: '弱敌', de: 'Schwach', fr: 'Faible', es: 'Débil', pt: 'Fraco', it: 'Debole', pl: 'Słaby', ru: 'Слабый', tr: 'Zayıf', th: 'อ่อนแอ' },

  // Relic/Potion tiers
  'Shop': { ja: 'ショップ', ko: '상점', zh: '商店', de: 'Laden', fr: 'Boutique', es: 'Tienda', pt: 'Loja', it: 'Negozio', pl: 'Sklep', ru: 'Магазин', tr: 'Mağaza', th: 'ร้านค้า' },
  'Event': { ja: 'イベント', ko: '이벤트', zh: '事件', de: 'Ereignis', fr: 'Événement', es: 'Evento', pt: 'Evento', it: 'Evento', pl: 'Zdarzenie', ru: 'Событие', tr: 'Etkinlik', th: 'เหตุการณ์' },
  'Tier': { ja: 'ティア', ko: '등급', zh: '级别', de: 'Stufe', fr: 'Niveau', es: 'Nivel', pt: 'Nível', it: 'Livello', pl: 'Poziom', ru: 'Уровень', tr: 'Seviye', th: 'ระดับ' },
  'Boss Swap': { ja: 'ボス交換', ko: '보스 교환', zh: 'Boss交换', de: 'Boss-Tausch', fr: 'Échange Boss', es: 'Intercambio de Jefe', pt: 'Troca de Chefe', it: 'Scambio Boss', pl: 'Wymiana bossa', ru: 'Обмен босса', tr: 'Patron Takası', th: 'แลกบอส' },

  // Event detail
  'Choices': { ja: '選択肢', ko: '선택지', zh: '选项', de: 'Optionen', fr: 'Choix', es: 'Opciones', pt: 'Opções', it: 'Scelte', pl: 'Wybory', ru: 'Варианты', tr: 'Seçenekler', th: 'ตัวเลือก' },
  'choices': { ja: '選択肢', ko: '선택지', zh: '个选项', de: 'Optionen', fr: 'choix', es: 'opciones', pt: 'opções', it: 'scelte', pl: 'wybory', ru: 'вариантов', tr: 'seçenek', th: 'ตัวเลือก' },

  // Footer / branding
  'a Slay the Spire companion': { ja: 'Slay the Spireの攻略サイト', ko: 'Slay the Spire 공략 사이트', zh: 'Slay the Spire 攻略网站', de: 'Ein Slay the Spire Begleiter', fr: 'Un compagnon Slay the Spire', es: 'Una guía de Slay the Spire', pt: 'Um companheiro de Slay the Spire', it: 'Un compagno di Slay the Spire', pl: 'Kompendium Slay the Spire', ru: 'Справочник Slay the Spire', tr: 'Bir Slay the Spire rehberi', th: 'คู่มือ Slay the Spire' },

  // Filter options
  'All colors': { ja: '全カラー', ko: '모든 색상', zh: '所有颜色', de: 'Alle Farben', fr: 'Toutes les couleurs', es: 'Todos los colores', pt: 'Todas as cores', it: 'Tutti i colori', pl: 'Wszystkie kolory', ru: 'Все цвета', tr: 'Tüm Renkler', th: 'ทุกสี' },
  'Colorless': { ja: '無色', ko: '무색', zh: '无色', de: 'Farblos', fr: 'Incolore', es: 'Sin color', pt: 'Incolor', it: 'Incolore', pl: 'Bezbarwna', ru: 'Бесцветная', tr: 'Renksiz', th: 'ไม่มีสี' },
  'Shared': { ja: '共有', ko: '공유', zh: '共享', de: 'Geteilt', fr: 'Partagé', es: 'Compartido', pt: 'Compartilhado', it: 'Condiviso', pl: 'Wspólny', ru: 'Общий', tr: 'Paylaşılan', th: 'ใช้ร่วม' },
  'Buff': { ja: 'バフ', ko: '버프', zh: '增益', de: 'Buff', fr: 'Bonus', es: 'Mejora', pt: 'Bônus', it: 'Potenziamento', pl: 'Wzmocnienie', ru: 'Усиление', tr: 'Güçlendirme', th: 'เสริม' },
  'Debuff': { ja: 'デバフ', ko: '디버프', zh: '减益', de: 'Debuff', fr: 'Malus', es: 'Debilitación', pt: 'Penalidade', it: 'Indebolimento', pl: 'Osłabienie', ru: 'Ослабление', tr: 'Zayıflatma', th: 'ลดทอน' },
  'game keywords and mechanics': { ja: 'ゲームキーワードと仕組み', ko: '게임 키워드 및 메커니즘', zh: '游戏关键词与机制', de: 'Spielbegriffe und Mechaniken', fr: 'Mots-clés et mécaniques du jeu', es: 'Palabras clave y mecánicas del juego', pt: 'Palavras-chave e mecânicas do jogo', it: 'Parole chiave e meccaniche di gioco', pl: 'Słowa kluczowe i mechaniki gry', ru: 'Ключевые слова и механики игры', tr: 'Oyun anahtar kelimeleri ve mekanikleri', th: 'คำสำคัญและกลไกของเกม' },
  'events from Slay the Spire 2': { ja: 'Slay the Spire 2 のイベント', ko: 'Slay the Spire 2 이벤트', zh: 'Slay the Spire 2 事件', de: 'Events aus Slay the Spire 2', fr: 'événements de Slay the Spire 2', es: 'eventos de Slay the Spire 2', pt: 'eventos de Slay the Spire 2', it: 'eventi di Slay the Spire 2', pl: 'wydarzeń z Slay the Spire 2', ru: 'событий из Slay the Spire 2', tr: 'Slay the Spire 2 etkinliği', th: 'อีเวนต์จาก Slay the Spire 2' },
  'events from Slay the Spire': { ja: 'Slay the Spire のイベント', ko: 'Slay the Spire 이벤트', zh: 'Slay the Spire 事件', de: 'Events aus Slay the Spire', fr: 'événements de Slay the Spire', es: 'eventos de Slay the Spire', pt: 'eventos de Slay the Spire', it: 'eventi di Slay the Spire', pl: 'wydarzeń z Slay the Spire', ru: 'событий из Slay the Spire', tr: 'Slay the Spire etkinliği', th: 'อีเวนต์จาก Slay the Spire' },
  'monsters from Slay the Spire 2': { ja: 'Slay the Spire 2 のモンスター', ko: 'Slay the Spire 2 몬스터', zh: 'Slay the Spire 2 怪物', de: 'Monster aus Slay the Spire 2', fr: 'monstres de Slay the Spire 2', es: 'monstruos de Slay the Spire 2', pt: 'monstros de Slay the Spire 2', it: 'mostri di Slay the Spire 2', pl: 'potworów z Slay the Spire 2', ru: 'монстров из Slay the Spire 2', tr: 'Slay the Spire 2 canavarı', th: 'มอนสเตอร์จาก Slay the Spire 2' },
  'The five playable characters of Slay the Spire 2.': { ja: 'Slay the Spire 2 の5人のプレイアブルキャラクター。', ko: 'Slay the Spire 2의 5명의 플레이어블 캐릭터.', zh: 'Slay the Spire 2 的五位可玩角色。', de: 'Die fünf spielbaren Charaktere von Slay the Spire 2.', fr: 'Les cinq personnages jouables de Slay the Spire 2.', es: 'Los cinco personajes jugables de Slay the Spire 2.', pt: 'Os cinco personagens jogáveis de Slay the Spire 2.', it: 'I cinque personaggi giocabili di Slay the Spire 2.', pl: 'Pięciu grywalnych bohaterów Slay the Spire 2.', ru: 'Пять игровых персонажей Slay the Spire 2.', tr: 'Slay the Spire 2\'nin beş oynanabilir karakteri.', th: 'ตัวละครที่เล่นได้ 5 ตัวของ Slay the Spire 2' },
  'The four playable characters of Slay the Spire.': { ja: 'Slay the Spire の4人のプレイアブルキャラクター。', ko: 'Slay the Spire의 4명의 플레이어블 캐릭터.', zh: 'Slay the Spire 的四位可玩角色。', de: 'Die vier spielbaren Charaktere von Slay the Spire.', fr: 'Les quatre personnages jouables de Slay the Spire.', es: 'Los cuatro personajes jugables de Slay the Spire.', pt: 'Os quatro personagens jogáveis de Slay the Spire.', it: 'I quattro personaggi giocabili di Slay the Spire.', pl: 'Czterech grywalnych bohaterów Slay the Spire.', ru: 'Четыре игровых персонажа Slay the Spire.', tr: 'Slay the Spire\'nin dört oynanabilir karakteri.', th: 'ตัวละครที่เล่นได้ 4 ตัวของ Slay the Spire' },
  'Energy / turn': { ja: 'エナジー / ターン', ko: '에너지 / 턴', zh: '能量 / 回合', de: 'Energie / Runde', fr: 'Énergie / tour', es: 'Energía / turno', pt: 'Energia / turno', it: 'Energia / turno', pl: 'Energia / turę', ru: 'Энергия / ход', tr: 'Enerji / tur', th: 'พลังงาน / เทิร์น' },
  'A hardened warrior who wields powerful attacks and self-healing. Starts with the most HP and excels at strength-based strategies.': { ja: '強力な攻撃と自己回復を操る歴戦の戦士。最も多くのHPでスタートし、筋力ベースの戦略に優れる。', ko: '강력한 공격과 자가 치유를 사용하는 노련한 전사. 가장 많은 HP로 시작하며 힘 기반 전략에 탁월합니다.', zh: '一位挥舞强力攻击与自我治愈的老练战士。拥有最高HP，擅长力量型策略。', de: 'Ein abgehärteter Krieger mit mächtigen Angriffen und Selbstheilung. Startet mit den meisten HP und glänzt bei Stärke-Strategien.', fr: 'Un guerrier endurci maniant attaques puissantes et auto-guérison. Commence avec le plus de PV et excelle dans les stratégies basées sur la force.', es: 'Un guerrero curtido que empuña ataques poderosos y autocuración. Comienza con más PV y destaca en estrategias basadas en fuerza.', pt: 'Um guerreiro resistente que usa ataques poderosos e autocura. Começa com mais PV e se destaca em estratégias baseadas em força.', it: 'Un guerriero temprato che impugna attacchi potenti e autoguarigione. Inizia con più PV ed eccelle nelle strategie basate sulla forza.', pl: 'Zahartowany wojownik z potężnymi atakami i samoleczeniem. Zaczyna z największą ilością HP i sprawdza się w strategiach opartych na sile.', ru: 'Закалённый воин с мощными атаками и самоисцелением. Начинает с наибольшим HP и преуспевает в силовых стратегиях.', tr: 'Güçlü saldırılar ve kendini iyileştirme kullanan deneyimli bir savaşçı. En fazla HP ile başlar ve güce dayalı stratejilerde öne çıkar.', th: 'นักรบผู้แกร่งกล้าที่ใช้การโจมตีทรงพลังและฟื้นฟูตนเอง เริ่มด้วย HP สูงสุดและเก่งกลยุทธ์พลัง' },
  'A deadly huntress who relies on poisons, shivs, and card draw. Starts with the largest deck and a focus on discard synergies.': { ja: '毒、シヴ、ドローに頼る致命的な女狩人。最大のデッキでスタートし、捨て札シナジーに重点を置く。', ko: '독, 단검, 카드 드로우에 의존하는 치명적인 사냥꾼. 가장 큰 덱으로 시작하며 버리기 시너지에 집중합니다.', zh: '依靠毒药、飞刀和抽牌的致命女猎手。以最大牌组开始，专注弃牌联动。', de: 'Eine tödliche Jägerin, die auf Gifte, Dolche und Kartenziehen setzt. Startet mit dem größten Deck und Fokus auf Abwurf-Synergien.', fr: 'Une chasseuse mortelle qui mise sur les poisons, les shivs et la pioche. Commence avec le plus grand deck et un focus sur les synergies de défausse.', es: 'Una cazadora letal que depende de venenos, puñales y robo de cartas. Comienza con el mazo más grande y enfoque en sinergias de descarte.', pt: 'Uma caçadora mortal que depende de venenos, adagas e compra de cartas. Começa com o maior baralho e foco em sinergias de descarte.', it: 'Una cacciatrice letale che si affida a veleni, pugnali e pesca carte. Inizia con il mazzo più grande e un focus sulle sinergie di scarto.', pl: 'Zabójcza łowczyni polegająca na truciznach, sztyletach i dobieraniu kart. Zaczyna z największą talią i synergią odrzucania.', ru: 'Смертоносная охотница, полагающаяся на яды, клинки и вытягивание карт. Начинает с самой большой колодой и синергиями сброса.', tr: 'Zehirlere, hançerlere ve kart çekmeye dayanan ölümcül bir avcı. En büyük desteyle başlar ve atma sinerjilerine odaklanır.', th: 'นักล่าผู้อันตรายที่พึ่งพายาพิษ มีดสั้น และการจั่วการ์ด เริ่มด้วยสำรับใหญ่สุดและเน้นซินเนอร์จีทิ้งการ์ด' },
  'An ancient automaton that channels elemental Orbs for passive and active effects. Unique focus on Lightning, Frost, Dark, and Plasma orbs.': { ja: '元素オーブをチャネルしてパッシブ・アクティブ効果を発揮する古代のオートマトン。ライトニング、フロスト、ダーク、プラズマオーブに特化。', ko: '원소 오브를 채널링하여 수동 및 능동 효과를 발휘하는 고대 자동인형. 번개, 서리, 어둠, 플라즈마 오브에 집중합니다.', zh: '一台引导元素球体产生被动和主动效果的古代机器人。专注于闪电、冰霜、暗影和等离子球。', de: 'Ein uralter Automat, der elementare Kugeln für passive und aktive Effekte kanalisiert. Einzigartiger Fokus auf Blitz-, Frost-, Dunkel- und Plasma-Kugeln.', fr: 'Un automate ancien qui canalise des orbes élémentaires pour des effets passifs et actifs. Focus unique sur les orbes Foudre, Givre, Ténèbres et Plasma.', es: 'Un autómata antiguo que canaliza orbes elementales para efectos pasivos y activos. Enfoque único en orbes de Rayo, Escarcha, Oscuridad y Plasma.', pt: 'Um autômato antigo que canaliza orbes elementais para efeitos passivos e ativos. Foco único em orbes de Relâmpago, Gelo, Trevas e Plasma.', it: 'Un antico automa che canalizza sfere elementali per effetti passivi e attivi. Focus unico su sfere Fulmine, Gelo, Oscurità e Plasma.', pl: 'Starożytny automat kanalizujący elementarne kule dla efektów pasywnych i aktywnych. Unikalny nacisk na kule Błyskawicy, Mrozu, Ciemności i Plazmy.', ru: 'Древний автоматон, направляющий элементальные сферы для пассивных и активных эффектов. Уникальный фокус на сферах Молнии, Мороза, Тьмы и Плазмы.', tr: 'Pasif ve aktif etkiler için elementel küreleri yönlendiren kadim bir otomat. Yıldırım, Buz, Karanlık ve Plazma kürelerine özgü odak.', th: 'หุ่นยนต์โบราณที่เชื่อมต่อออร์บธาตุเพื่อเอฟเฟกต์เชิงรุกและรับ เน้นออร์บสายฟ้า น้ำแข็ง มืด และพลาสมา' },
  'A blind ascetic who shifts between powerful Stances. Wrath doubles damage dealt and taken, while Calm grants energy on exit.': { ja: '強力なスタンスを切り替える盲目の行者。憤怒は与える・受けるダメージを倍増させ、平静は解除時にエナジーを得る。', ko: '강력한 자세를 전환하는 맹인 수행자. 분노는 주고받는 피해를 두 배로 하고, 평온은 해제 시 에너지를 줍니다.', zh: '在强大姿态间切换的盲目苦行者。愤怒使造成和承受的伤害翻倍，而冷静在退出时获得能量。', de: 'Eine blinde Asketin, die zwischen mächtigen Haltungen wechselt. Zorn verdoppelt verursachten und erlittenen Schaden, Ruhe gewährt Energie beim Verlassen.', fr: 'Une ascète aveugle qui alterne entre des postures puissantes. Colère double les dégâts infligés et subis, tandis que Calme octroie de l\'énergie en sortant.', es: 'Una asceta ciega que alterna entre posturas poderosas. Ira duplica el daño infligido y recibido, mientras que Calma otorga energía al salir.', pt: 'Uma asceta cega que alterna entre posturas poderosas. Fúria dobra o dano causado e recebido, enquanto Calma concede energia ao sair.', it: 'Un\'asceta cieca che alterna tra potenti posizioni. Ira raddoppia i danni inflitti e subiti, mentre Calma concede energia all\'uscita.', pl: 'Niewidoma ascetka przełączająca się między potężnymi postawami. Gniew podwaja zadane i otrzymane obrażenia, a Spokój daje energię przy wyjściu.', ru: 'Слепая аскет, переключающаяся между мощными стойками. Гнев удваивает наносимый и получаемый урон, а Спокойствие даёт энергию при выходе.', tr: 'Güçlü duruşlar arasında geçiş yapan kör bir çileci. Gazap verilen ve alınan hasarı ikiye katlar, Sükunet çıkışta enerji verir.', th: 'นักพรตตาบอดที่สลับระหว่างท่าทรงพลัง พิโรธเพิ่มความเสียหายที่ให้และรับเป็นสองเท่า สงบให้พลังงานเมื่อออก' },
  'A dark summoner who commands Osty and raises undead minions. Manipulates souls and sacrifices allies for power.': { ja: 'オスティを従え、アンデッドミニオンを召喚するダークサモナー。魂を操り仲間を犠牲に力を得る。', ko: '오스티를 지휘하고 언데드 미니언을 소환하는 어둠의 소환사. 영혼을 조종하고 아군을 희생시켜 힘을 얻음.', zh: '指挥奥斯提并召唤亡灵仆从的暗黑召唤师。操纵灵魂，牺牲盟友获取力量。', de: 'Ein dunkler Beschwörer, der Osty befehligt und Untote herbeiruft. Manipuliert Seelen und opfert Verbündete für Macht.', fr: 'Un invocateur sombre qui commande Osty et lève des morts-vivants. Manipule les âmes et sacrifie des alliés pour le pouvoir.', es: 'Un invocador oscuro que comanda a Osty y levanta no-muertos. Manipula almas y sacrifica aliados por poder.', pt: 'Um invocador sombrio que comanda Osty e ergue mortos-vivos. Manipula almas e sacrifica aliados por poder.', it: 'Un evocatore oscuro che comanda Osty e risveglia non-morti. Manipola anime e sacrifica alleati per potere.', pl: 'Mroczny przywoływacz dowodzący Ostym i wskrzeszający nieumarłych. Manipuluje duszami i poświęca sojuszników dla mocy.', ru: 'Тёмный призыватель, командующий Ости и поднимающий нежить. Манипулирует душами и жертвует союзниками ради силы.', tr: 'Osty\'yi yöneten ve ölümsüz uşaklar çağıran karanlık büyücü. Ruhları manipüle eder ve güç için müttefikleri feda eder.', th: 'ผู้เรียกมืดที่บัญชาออสตีและปลุกมินเนียนอันเดด ควบคุมวิญญาณและเสียสละพันธมิตรเพื่อพลัง' },
  'A celestial ruler who harnesses Stars for powerful abilities. Balances resource management with explosive turns.': { ja: '星の力を操る天上の支配者。リソース管理と爆発的なターンのバランスを取る。', ko: '별의 힘을 다루는 천상의 통치자. 자원 관리와 폭발적인 턴의 균형.', zh: '驾驭星辰之力的天界统治者。在资源管理与爆发回合间取得平衡。', de: 'Ein himmlischer Herrscher, der Sterne für mächtige Fähigkeiten nutzt. Balance zwischen Ressourcenmanagement und explosiven Runden.', fr: 'Un souverain céleste qui exploite les Étoiles pour des capacités puissantes. Équilibre entre gestion des ressources et tours explosifs.', es: 'Un gobernante celestial que aprovecha las Estrellas. Equilibra la gestión de recursos con turnos explosivos.', pt: 'Um governante celestial que usa Estrelas para habilidades poderosas. Equilibra gestão de recursos com turnos explosivos.', it: 'Un sovrano celeste che sfrutta le Stelle per abilità potenti. Bilancia gestione risorse e turni esplosivi.', pl: 'Niebiański władca wykorzystujący Gwiazdy do potężnych zdolności. Równoważy zarządzanie zasobami z wybuchowymi turami.', ru: 'Небесный правитель, использующий Звёзды для мощных способностей. Баланс между управлением ресурсами и взрывными ходами.', tr: 'Güçlü yetenekler için Yıldızları kullanan göksel hükümdar. Kaynak yönetimi ile patlayıcı turlar arasında denge kurar.', th: 'ผู้ปกครองสวรรค์ที่ใช้ดาวเพื่อความสามารถอันทรงพลัง สมดุลระหว่างการจัดการทรัพยากรกับเทิร์นระเบิด' },
  'Positive Blessings (2 offered per run)': { ja: 'ポジティブな祝福（各ランで2つ提供）', ko: '긍정적 축복 (런당 2개 제공)', zh: '正面祝福（每次冒险提供2个）', de: 'Positive Segnungen (2 pro Lauf angeboten)', fr: 'Bénédictions positives (2 offertes par aventure)', es: 'Bendiciones positivas (2 ofrecidas por partida)', pt: 'Bênçãos positivas (2 oferecidas por corrida)', it: 'Benedizioni positive (2 offerte per run)', pl: 'Pozytywne błogosławieństwa (2 oferowane na bieg)', ru: 'Положительные благословения (2 предложены за забег)', tr: 'Olumlu kutsamalar (koşu başına 2 sunulur)', th: 'พรดี (เสนอ 2 ต่อรอบ)' },
  'Cursed Blessings (1 offered per run)': { ja: '呪いの祝福（各ランで1つ提供）', ko: '저주받은 축복 (런당 1개 제공)', zh: '诅咒祝福（每次冒险提供1个）', de: 'Verfluchte Segnungen (1 pro Lauf angeboten)', fr: 'Bénédictions maudites (1 offerte par aventure)', es: 'Bendiciones malditas (1 ofrecida por partida)', pt: 'Bênçãos amaldiçoadas (1 oferecida por corrida)', it: 'Benedizioni maledette (1 offerta per run)', pl: 'Przeklęte błogosławieństwa (1 oferowane na bieg)', ru: 'Проклятые благословения (1 предложено за забег)', tr: 'Lanetli kutsamalar (koşu başına 1 sunulur)', th: 'พรสาป (เสนอ 1 ต่อรอบ)' },
  'Token': { ja: 'トークン', ko: '토큰', zh: '衍生', de: 'Spielstein', fr: 'Jeton', es: 'Ficha', pt: 'Ficha', it: 'Gettone', pl: 'Żeton', ru: 'Жетон', tr: 'Jeton', th: 'โทเค็น' },
  'View Upgrades': { ja: 'アップグレードを表示', ko: '업그레이드 보기', zh: '查看升级', de: 'Aufwertungen anzeigen', fr: 'Voir les améliorations', es: 'Ver mejoras', pt: 'Ver melhorias', it: 'Vedi potenziamenti', pl: 'Pokaż ulepszenia', ru: 'Показать улучшения', tr: 'Yükseltmeleri Göster', th: 'ดูอัปเกรด' },
  'Ancient': { ja: 'エンシェント', ko: '고대', zh: '远古', de: 'Uralte', fr: 'Ancienne', es: 'Antigua', pt: 'Antiga', it: 'Antica', pl: 'Starożytna', ru: 'Древняя', tr: 'Kadim', th: 'โบราณ' },

  // Card keywords (from game localization)
  'Exhaust': { ja: '廃棄', ko: '소멸', zh: '消耗', de: 'Erschöpft', fr: 'Épuisement', es: 'Agotamiento', pt: 'Exaurir', it: 'Esaurimento', pl: 'Wyczerpanie', ru: 'Сжигается', tr: 'Tüket', th: 'สลาย' },
  'Ethereal': { ja: 'エセリアル', ko: '휘발성', zh: '虚无', de: 'Flüchtig', fr: 'Éthéré', es: 'Etérea', pt: 'Etérea', it: 'Evanescenza', pl: 'Eteryczna', ru: 'Эфирная', tr: 'Ruhani', th: 'กึ่งสลาย' },
  'Innate': { ja: '天賦', ko: '선천성', zh: '固有', de: 'Angeboren', fr: 'Inné', es: 'Innata', pt: 'Inata', it: 'Innatismo', pl: 'Startowa', ru: 'Начальная', tr: 'Yerleşik', th: 'ติดตัว' },
  'Retain': { ja: '保留', ko: '보존', zh: '保留', de: 'Behalten', fr: 'Retenue', es: 'Retención', pt: 'Manter', it: 'Conservazione', pl: 'Zachowanie', ru: 'Оставляется', tr: 'Sakla', th: 'คงสภาพ' },
  'Eternal': { ja: '永劫', ko: '영구', zh: '永恒', de: 'Ewig', fr: 'Éternel', es: 'Eterna', pt: 'Perpétua', it: 'Eternità', pl: 'Wieczna', ru: 'Вечная', tr: 'Sonsuz', th: 'นิรันดร์' },
  'Sly': { ja: 'スライ', ko: '교활', zh: '奇巧', de: 'Listig', fr: 'Ruse', es: 'Astucia', pt: 'Sagaz', it: 'Astuzia', pl: 'Chytra', ru: 'Коварная', tr: 'Kurnaz', th: 'เล่ห์เหลี่ยม' },
  'Unplayable': { ja: 'プレイ不可', ko: '사용불가', zh: '不能被打出', de: 'Unspielbar', fr: 'Injouable', es: 'Injugable', pt: 'Injogável', it: 'Ingiocabilità', pl: 'Niezagrywalna', ru: 'Неиграбельная', tr: 'Oynanamaz', th: 'ถูกผนึก' },
  'Purge on use': { ja: '使用時廃棄', ko: '사용 시 제거', zh: '使用后移除', de: 'Verbrauch', fr: 'Purge à l\'utilisation', es: 'Purgar al usar', pt: 'Purgar ao usar', it: 'Purga all\'uso', pl: 'Oczyszczenie po użyciu', ru: 'Удаляется при использовании', tr: 'Kullanınca arındır', th: 'ล้างเมื่อใช้' },
  'Self Retain': { ja: '自己保留', ko: '자체 보존', zh: '自我保留', de: 'Selbstbehalt', fr: 'Auto-retenue', es: 'Auto-retención', pt: 'Auto-manutenção', it: 'Auto-conservazione', pl: 'Samozachowanie', ru: 'Самосохранение', tr: 'Kendini sakla', th: 'คงสภาพตัวเอง' },

  // Explorer UI
  'Loading…': { ja: '読み込み中…', ko: '로딩 중…', zh: '加载中…', de: 'Laden…', fr: 'Chargement…', es: 'Cargando…', pt: 'Carregando…', it: 'Caricamento…', pl: 'Ładowanie…', ru: 'Загрузка…', tr: 'Yükleniyor…', th: 'กำลังโหลด…' },
  'results': { ja: '件', ko: '개 결과', zh: '个结果', de: 'Ergebnisse', fr: 'résultats', es: 'resultados', pt: 'resultados', it: 'risultati', pl: 'wyników', ru: 'результатов', tr: 'sonuç', th: 'ผลลัพธ์' },
  'Prev': { ja: '前へ', ko: '이전', zh: '上一页', de: 'Zurück', fr: 'Précédent', es: 'Anterior', pt: 'Anterior', it: 'Precedente', pl: 'Poprzednia', ru: 'Назад', tr: 'Önceki', th: 'ก่อนหน้า' },
  'Next': { ja: '次へ', ko: '다음', zh: '下一页', de: 'Weiter', fr: 'Suivant', es: 'Siguiente', pt: 'Próximo', it: 'Successivo', pl: 'Następna', ru: 'Далее', tr: 'Sonraki', th: 'ถัดไป' },
  'Cost (exact)': { ja: 'コスト（指定）', ko: '비용 (정확)', zh: '费用（精确）', de: 'Kosten (exakt)', fr: 'Coût (exact)', es: 'Coste (exacto)', pt: 'Custo (exato)', it: 'Costo (esatto)', pl: 'Koszt (dokładny)', ru: 'Стоимость (точная)', tr: 'Maliyet (tam)', th: 'ค่าใช้จ่าย (แน่นอน)' },
  'Search cards, relics, events…': { ja: 'カード、レリック、イベントを検索…', ko: '카드, 유물, 이벤트 검색…', zh: '搜索卡牌、遗物、事件…', de: 'Karten, Relikte, Ereignisse suchen…', fr: 'Rechercher cartes, reliques, événements…', es: 'Buscar cartas, reliquias, eventos…', pt: 'Buscar cartas, relíquias, eventos…', it: 'Cerca carte, reliquie, eventi…', pl: 'Szukaj kart, reliktów, zdarzeń…', ru: 'Поиск карт, реликвий, событий…', tr: 'Kart, kalıntı, etkinlik ara…', th: 'ค้นหาการ์ด, เรลิค, เหตุการณ์…' },
  'No results for': { ja: '該当なし:', ko: '결과 없음:', zh: '无结果:', de: 'Keine Ergebnisse für', fr: 'Aucun résultat pour', es: 'Sin resultados para', pt: 'Nenhum resultado para', it: 'Nessun risultato per', pl: 'Brak wyników dla', ru: 'Нет результатов для', tr: 'Sonuç bulunamadı:', th: 'ไม่พบผลลัพธ์สำหรับ' },
  'Browse': { ja: 'ブラウズ', ko: '탐색', zh: '浏览', de: 'Durchsuchen', fr: 'Parcourir', es: 'Explorar', pt: 'Navegar', it: 'Sfoglia', pl: 'Przeglądaj', ru: 'Обзор', tr: 'Göz At', th: 'เรียกดู' },
  'cards across all characters': { ja: '全キャラクターのカード', ko: '모든 캐릭터의 카드', zh: '所有角色的卡牌', de: 'Karten aller Charaktere', fr: 'cartes de tous les personnages', es: 'cartas de todos los personajes', pt: 'cartas de todos os personagens', it: 'carte di tutti i personaggi', pl: 'kart wszystkich postaci', ru: 'карт всех персонажей', tr: 'tüm karakterlerin kartları', th: 'การ์ดของทุกตัวละคร' },
  'Upgrade Changes': { ja: 'アップグレード変更', ko: '업그레이드 변경', zh: '升级变化', de: 'Aufwertungsänderungen', fr: "Modifications d'amélioration", es: 'Cambios de mejora', pt: 'Mudanças de melhoria', it: 'Modifiche potenziamento', pl: 'Zmiany ulepszenia', ru: 'Изменения улучшения', tr: 'Yükseltme Değişiklikleri', th: 'การเปลี่ยนแปลงอัปเกรด' },
  'Tags': { ja: 'タグ', ko: '태그', zh: '标签', de: 'Tags', fr: 'Tags', es: 'Etiquetas', pt: 'Tags', it: 'Tag', pl: 'Tagi', ru: 'Теги', tr: 'Etiketler', th: 'แท็ก' },

  // Misc
  'Description': { ja: '説明', ko: '설명', zh: '描述', de: 'Beschreibung', fr: 'Description', es: 'Descripción', pt: 'Descrição', it: 'Descrizione', pl: 'Opis', ru: 'Описание', tr: 'Açıklama', th: 'คำอธิบาย' },
  'Flavor': { ja: 'フレーバー', ko: '플레이버', zh: '背景', de: 'Beschreibung', fr: 'Ambiance', es: 'Ambientación', pt: 'Sabor', it: 'Ambientazione', pl: 'Opis fabularny', ru: 'Описание', tr: 'Lezzet', th: 'รสชาติ' },
  'Back to': { ja: '戻る:', ko: '돌아가기:', zh: '返回', de: 'Zurück zu', fr: 'Retour à', es: 'Volver a', pt: 'Voltar para', it: 'Torna a', pl: 'Powrót do', ru: 'Назад к', tr: 'Geri dön:', th: 'กลับไป' },
  'Cards that apply': { ja: '関連カード:', ko: '적용 카드:', zh: '相关卡牌:', de: 'Karten mit', fr: 'Cartes appliquant', es: 'Cartas que aplican', pt: 'Cartas que aplicam', it: 'Carte che applicano', pl: 'Karty stosujące', ru: 'Карты с эффектом', tr: 'Uygulayan kartlar:', th: 'การ์ดที่ใช้' },
  'See keyword definition': { ja: 'キーワード定義を見る', ko: '키워드 정의 보기', zh: '查看关键词定义', de: 'Keyword-Definition ansehen', fr: 'Voir la définition du mot-clé', es: 'Ver definición de palabra clave', pt: 'Ver definição da palavra-chave', it: 'Vedi definizione parola chiave', pl: 'Zobacz definicję słowa kluczowego', ru: 'См. определение ключевого слова', tr: 'Anahtar kelime tanımını gör', th: 'ดูคำจำกัดความ' },

  // STS2 index page
  'The complete database for Slay the Spire 2': { ja: 'Slay the Spire 2の完全データベース', ko: 'Slay the Spire 2 완전 데이터베이스', zh: 'Slay the Spire 2 完整数据库', de: 'Die komplette Datenbank für Slay the Spire 2', fr: 'La base de données complète de Slay the Spire 2', es: 'La base de datos completa de Slay the Spire 2', pt: 'O banco de dados completo de Slay the Spire 2', it: 'Il database completo di Slay the Spire 2', pl: 'Kompletna baza danych Slay the Spire 2', ru: 'Полная база данных Slay the Spire 2', tr: 'Slay the Spire 2 tam veritabanı', th: 'ฐานข้อมูลที่สมบูรณ์ของ Slay the Spire 2' },
  'Strength & self-healing': { ja: '筋力と自己回復', ko: '힘과 자가 치유', zh: '力量与自愈', de: 'Stärke & Selbstheilung', fr: 'Force et auto-guérison', es: 'Fuerza y autocuración', pt: 'Força e autocura', it: 'Forza e autocura', pl: 'Siła i samoleczenie', ru: 'Сила и самоисцеление', tr: 'Güç ve kendini iyileştirme', th: 'พลังและการฟื้นฟูตัวเอง' },
  'Poison & card draw': { ja: '毒とカードドロー', ko: '독과 카드 드로우', zh: '毒与抽牌', de: 'Gift & Kartenziehen', fr: 'Poison et pioche', es: 'Veneno y robo de cartas', pt: 'Veneno e compra de cartas', it: 'Veleno e pesca carte', pl: 'Trucizna i dobieranie', ru: 'Яд и добор карт', tr: 'Zehir ve kart çekme', th: 'พิษและดึงการ์ด' },
  'Orbs & channeling': { ja: 'オーブとチャネリング', ko: '오브와 채널링', zh: '球体与引导', de: 'Orbs & Kanalisierung', fr: 'Orbes et canalisation', es: 'Orbes y canalización', pt: 'Orbes e canalização', it: 'Sfere e incanalamento', pl: 'Kule i kanałowanie', ru: 'Сферы и направление', tr: 'Küre ve kanalize etme', th: 'ออร์บและชาแนล' },
  'Summons & sacrifice': { ja: '召喚と犠牲', ko: '소환과 희생', zh: '召唤与牺牲', de: 'Beschwörungen & Opfer', fr: 'Invocations et sacrifice', es: 'Invocaciones y sacrificio', pt: 'Invocações e sacrifício', it: 'Evocazioni e sacrificio', pl: 'Przywołania i poświęcenie', ru: 'Призыв и жертва', tr: 'Çağırma ve feda', th: 'เรียกและเสียสละ' },
  'Stars & burst turns': { ja: '星とバーストターン', ko: '별과 폭발 턴', zh: '星辰与爆发回合', de: 'Sterne & Burst-Runden', fr: 'Étoiles et tours explosifs', es: 'Estrellas y turnos explosivos', pt: 'Estrelas e turnos explosivos', it: 'Stelle e turni esplosivi', pl: 'Gwiazdy i wybuchy', ru: 'Звёзды и взрывные ходы', tr: 'Yıldızlar ve patlama turları', th: 'ดาวและเทิร์นระเบิด' },
  'relics': { ja: 'レリック', ko: '유물', zh: '遗物', de: 'Relikte', fr: 'reliques', es: 'reliquias', pt: 'relíquias', it: 'reliquie', pl: 'reliktów', ru: 'реликвий', tr: 'kalıntı', th: 'เรลิค' },
  'potions': { ja: 'ポーション', ko: '물약', zh: '药水', de: 'Tränke', fr: 'potions', es: 'pociones', pt: 'poções', it: 'pozioni', pl: 'mikstur', ru: 'зелий', tr: 'iksir', th: 'ยา' },
  'monsters': { ja: 'モンスター', ko: '몬스터', zh: '怪物', de: 'Monster', fr: 'monstres', es: 'monstruos', pt: 'monstros', it: 'mostri', pl: 'potworów', ru: 'монстров', tr: 'canavar', th: 'มอนสเตอร์' },
  'events': { ja: 'イベント', ko: '이벤트', zh: '事件', de: 'Ereignisse', fr: 'événements', es: 'eventos', pt: 'eventos', it: 'eventi', pl: 'zdarzeń', ru: 'событий', tr: 'etkinlik', th: 'เหตุการณ์' },
  'buffs & debuffs': { ja: 'バフ＆デバフ', ko: '버프 & 디버フ', zh: '增益与减益', de: 'Buffs & Debuffs', fr: 'effets', es: 'efectos', pt: 'efeitos', it: 'effetti', pl: 'efektów', ru: 'эффектов', tr: 'etki', th: 'บัฟและดีบัฟ' },
  'card enchantments': { ja: 'カードエンチャント', ko: 'カード 인챈트', zh: '卡牌附魔', de: 'Kartenverzauberungen', fr: 'enchantements de carte', es: 'encantamientos de carta', pt: 'encantamentos de carta', it: 'incantesimi carta', pl: 'zaklęć kart', ru: 'зачарований карт', tr: 'kart büyüsü', th: 'เสน่ห์การ์ด' },
  'keywords': { ja: 'キーワード', ko: '키워드', zh: '关键词', de: 'Schlüsselwörter', fr: 'mots-clés', es: 'palabras clave', pt: 'palavras-chave', it: 'parole chiave', pl: 'słów kluczowych', ru: 'ключевых слов', tr: 'anahtar kelime', th: 'คำสำคัญ' },

  // Page subtitles & headings
  'Buffs, debuffs, and passive effects in STS2.': { ja: 'STS2のバフ、デバフ、パッシブ効果。', ko: 'STS2의 버프, 디버프 및 패시브 효과.', zh: 'STS2中的增益、减益和被动效果。', de: 'Buffs, Debuffs und passive Effekte in STS2.', fr: 'Buffs, débuffs et effets passifs dans STS2.', es: 'Buffs, debuffs y efectos pasivos en STS2.', pt: 'Buffs, debuffs e efeitos passivos em STS2.', it: 'Buff, debuff ed effetti passivi in STS2.', pl: 'Buffy, debuffy i efekty pasywne w STS2.', ru: 'Баффы, дебаффы и пассивные эффекты в STS2.', tr: 'STS2\'deki buff, debuff ve pasif etkiler.', th: 'บัฟ ดีบัฟ และเอฟเฟกต์แฝงใน STS2' },
  'Card enchantments that can be applied at Rest Sites.': { ja: '休憩所で付与できるカードエンチャント。', ko: '휴식 장소에서 적용할 수 있는 카드 인챈트.', zh: '可在篝火处施加的卡牌附魔。', de: 'Kartenverzauberungen, die an Rastplätzen angewendet werden.', fr: 'Enchantements de carte applicables aux Sites de repos.', es: 'Encantamientos de carta aplicables en Sitios de descanso.', pt: 'Encantamentos de carta aplicáveis em Locais de descanso.', it: 'Incantesimi carta applicabili ai Siti di riposo.', pl: 'Zaklęcia kart stosowane na Miejscach odpoczynku.', ru: 'Зачарования карт, доступные на Местах отдыха.', tr: 'Dinlenme Noktalarında uygulanabilen kart büyüleri.', th: 'เสน่ห์การ์ดที่สามารถใช้ได้ที่จุดพักผ่อน' },
  'Reference': { ja: 'リファレンス', ko: '참조', zh: '参考', de: 'Referenz', fr: 'Référence', es: 'Referencia', pt: 'Referência', it: 'Riferimento', pl: 'Referencja', ru: 'Справочник', tr: 'Referans', th: 'อ้างอิง' },
  'Orbs': { ja: 'オーブ', ko: '오브', zh: '球体', de: 'Orbs', fr: 'Orbes', es: 'Orbes', pt: 'Orbes', it: 'Sfere', pl: 'Kule', ru: 'Сферы', tr: 'Küreler', th: 'ออร์บ' },
  'Stances': { ja: 'スタンス', ko: '자세', zh: '姿态', de: 'Haltungen', fr: 'Postures', es: 'Posturas', pt: 'Posturas', it: 'Posizioni', pl: 'Postawy', ru: 'Стойки', tr: 'Duruşlar', th: 'ท่าทาง' },
  'Blights': { ja: 'ブライト', ko: '역병', zh: '灾厄', de: 'Seuchen', fr: 'Fléaux', es: 'Plagas', pt: 'Pragas', it: 'Flagelli', pl: 'Plagi', ru: 'Порчи', tr: 'Belalar', th: 'ภัยพิบัติ' },
  'Achievements': { ja: '実績', ko: '업적', zh: '成就', de: 'Erfolge', fr: 'Succès', es: 'Logros', pt: 'Conquistas', it: 'Obiettivi', pl: 'Osiągnięcia', ru: 'Достижения', tr: 'Başarımlar', th: 'ความสำเร็จ' },
  'Starting Powers': { ja: '初期パワー', ko: '시작 능력', zh: '初始能力', de: 'Startkräfte', fr: 'Pouvoirs de départ', es: 'Poderes iniciales', pt: 'Poderes iniciais', it: 'Poteri iniziali', pl: 'Startowe moce', ru: 'Начальные силы', tr: 'Başlangıç Güçleri', th: 'พลังเริ่มต้น' },
  'Pool': { ja: 'プール', ko: '풀', zh: '池', de: 'Pool', fr: 'Pool', es: 'Pool', pt: 'Pool', it: 'Pool', pl: 'Pula', ru: 'Пул', tr: 'Havuz', th: 'พูล' },
  // Section headings
};

/**
 * Translate a UI string key to the given locale.
 * Returns the English key if no translation exists.
 */
export function t(key: string, locale: Locale | string = 'en'): string {
  if (locale === 'en') return key;
  return strings[key]?.[locale as Locale] ?? key;
}

/**
 * Get all translations as a flat object for client-side use.
 * Only includes strings that differ from English for the given locale.
 */
export function getTranslations(locale: Locale | string): Record<string, string> {
  if (locale === 'en') return {};
  const result: Record<string, string> = {};
  for (const [key, translations] of Object.entries(strings)) {
    const val = translations[locale as Locale];
    if (val) result[key] = val;
  }
  return result;
}
